timezone = "America/Toronto"
#                  ┌───────────── sec (0 - 59)
#                  │ ┌───────────── minute (0 - 59)
#                  │ │ ┌───────────── hour (0 - 23)
#                  │ │ │ ┌───────────── day of the month (1 - 31)
#                  │ │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#                  │ │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#                  │ │ │ │ │ │ ┌───────────── year
#                  │ │ │ │ │ │ │
#                  │ │ │ │ │ │ │
#                  * * * * * * *

[tasks.water]
name = 'Drink water (min 1 litre)'
cron_expression = '0 30 9 * * * *'

[tasks.light_therapy]
name = "Light therapy x1"
cron_expression = '0 30 9 * * 1-5 *'

[tasks.recycling_green_bin]
cron_expression = "0 30 9 1-7,16-21 * 4 *"
name = "Garbage, Green bin"

[tasks.garbage_green_bin]
cron_expression = "0 30 9 8-15,22-31 * 4 *"
name = "Recycling, Green bin"

[tasks.rent]
cron_expression = "0 30 9 28 * * *"
name = "Pay rent"

[tasks.joint_account]
cron_expression = "0 30 9 28 * * *"
name = "Pay joint account contribution"

[tasks.credit_card]
cron_expression = "0 30 9 28 * * *"
name = "Pay credit card"

[tasks.taxes]
cron_expression = "0 30 9 15 3 * *"
name = "Pay taxes"

[tasks.passwords]
cron_expression = "0 30 9 15 12 * *"
name = "Rotate passwords"

[tasks.personal_goals]
cron_expression = "0 30 9 8-15 * 6 *"
name = "Check personal goals trello"

[tasks.book_list]
cron_expression = "0 30 9 15-21 * 6 *"
name = "Update book list"

[tasks.daybook_setup]
cron_expression = "0 30 9 * * 6 *"
name = "Setup daybook for next week."

[tasks.cedar_meds]
cron_expression = "0 30 9 1 * * *"
name = "Give Cedar his Fea and tick medication"


# Using this an example because I don't want to commit a real birthday into
# what may become a public repo.
[birthdays.canada]
name = "Canada's birthday"
cron_expression = '0 * * 1 7 * *'
