name: Build and Test

on: [push]

jobs:
  typecheck-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run the program to validate the tasks file
      run: cargo run -- --tasks tasks/personal.toml

