name: Send Email

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/10 * * * *'

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run the program
      run: cargo run -- --source tasks/personal.toml > output.txt

    - name: SendGrid
      uses: peter-evans/sendgrid-action@v1
      env:
        SENDGRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
